version: "3"

services:
  redis:
    image: redis:4.0.14
    restart: always
    expose:
      - "6379"

  celery_worker:
    image: cnas-app:latest
    restart: always
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDBEAT_DB: 0
      BROKER_DB: 0
      RESULT_DB: 0
    command: ["worker"]

  # celery_beats:
  #   image: cnas-app:latest
  #   restart: always
  #   depends_on:
  #     - redis
  #     - celery_worker
  #   environment:
  #     REDIS_HOST: redis
  #     REDIS_PORT: 6379
  #     REDBEAT_DB: 0
  #     BROKER_DB: 0
  #     RESULT_DB: 0
  #   command: ["beat"]

  web:
    image: cnas-app:latest
    restart: always
    depends_on:
      - redis
      - celery_worker
    environment:
      WEB_PORT: 5000
    ports:
      - "5000:5000"
    command: ["flask"]
