version: "3"

services:
  rabbitmq:
    image: rabbitmq:3.7.15-management
    restart: always
    expose:
      - "5672"
    ports:
      - "15672:15672"

  celery_worker:
    image: cnas-app:latest
    restart: always
    depends_on:
      - rabbitmq
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
    command: ["worker"]

  web:
    image: cnas-app:latest
    restart: always
    depends_on:
      - rabbitmq
      - celery_worker
    environment:
      WEB_PORT: 5000
    ports:
      - "5000:5000"
    command: ["flask"]
